### ISSUE TITLE
boost dependency is outdated

### ISSUE THREAD

**Issue by xeechou** [LizardByte/pacman-repo#21] opened 2024-09-26 13:55 UTC
### Describe the Bug

Launching sunshine from command line gives following error:
```
sunshine: error while loading shared libraries: libboost_locale.so.1.83.0: cannot open shared object file: No such file or directory
```

Double check the system boost gives: 

```
-rw-r--r-- 1 root root 3.2M Sep 25 08:04 /usr/lib/libboost_locale.a
lrwxrwxrwx 1 root root   25 Sep 25 08:04 /usr/lib/libboost_locale.so -> libboost_locale.so.1.86.0
-rwxr-xr-x 1 root root 647K Sep 25 08:04 /usr/lib/libboost_locale.so.1.86.0
```
 
The boost dependency is outdated

### Expected Behavior

sunshine app run as normal.

**Comment by ReenigneArcher** [comment] 2024-09-26 14:50
Duplicate of #19

**Closed by ReenigneArcher** 2024-09-26 14:50 UTC
